# Set the port to the PORT environment variable
server:
  port: ${PORT:8080}

spring:
  security:
    oauth2:
      client:
       registration:
         google:
           client-id: <app-client-id>
           client-secret: <app-client-secret>
